### ISSUE TITLE
bug(compile): 0.5.0 cannot compile .gr file

### ISSUE THREAD

**Issue by Guikingone** [grain-lang/grain#1315]
Hi 👋🏻 

I downloaded the `0.5.0` release yesterday and when launching `grain hello.gr`, the following error is displayed:

```bash
/snapshot/grain/cli/bin/grainc.js: internal error, uncaught exception:
                                   Invalid_argument("Types.value_description.val_global")

node:child_process:905
    throw err;
    ^

Error: Command failed: "/usr/local/bin/grain" /snapshot/grain/cli/bin/grainc.js --stdlib /snapshot/grain/stdlib hello.gr
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at execSync (pkg/prelude/bootstrap.js:2072:30)
    at Object.execGrainc [as grainc] (/snapshot/grain/cli/bin/exec.js:38:10)
    at GrainCommand.<anonymous> (/snapshot/grain/cli/bin/grain.js:200:10)
    at GrainCommand.listener [as _actionHandler] (/snapshot/grain/node_modules/commander/lib/command.js:488:17)
    at /snapshot/grain/node_modules/commander/lib/command.js:1227:65
    at GrainCommand._chainOrCall (/snapshot/grain/node_modules/commander/lib/command.js:1144:12)
    at GrainCommand._parseCommand (/snapshot/grain/node_modules/commander/lib/command.js:1227:27)
    at GrainCommand._dispatchSubcommand (/snapshot/grain/node_modules/commander/lib/command.js:1050:25) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1507,
  stdout: null,
  stderr: null
}
```

**Platform**: macOS 12.4
**Chip**: M1 Pro

The installation process was tested with both Homebrew and the "classic one": https://grain-lang.org/docs/getting_grain#MacOS-x64---Download.

Thanks again and have a great day 🙂

**Comment by phated** [comment]
This will be fixed with #1314

You are compiling a project that you compiled with a previous version of the compiler, right? You need to delete old artifacts, such as the target/ directory and wasm files.
