### ISSUE TITLE
`grain doc` fails upon seeing type alias

### ISSUE THREAD

**Issue by alexsnezhko3** [grain-lang/grain#1366]
As the title suggests, it looks like `grain doc` doesn't work if there are any `type`s defined in the file. A minimal example:
```
/**
 * This is my type alias
 */
export type MyType = (String) -> String

/**
 * This is a function
 */
export let f: MyType = (a) => a ++ a

print(f("abc"))
```
This file compiles and runs fine, but when I run `grain doc` on it I get this error:
```
Failure("NYI: Otyp_arrow pretty-printer")
node:child_process:905
    throw err;
    ^

Error: Command failed: "/usr/local/bin/grain" /snapshot/grain/cli/bin/graindoc.js --stdlib /snapshot/grain/stdlib -o asdf.md asdf.gr
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at execSync (pkg/prelude/bootstrap.js:2072:30)
    at GrainCommand.execGraindoc (/snapshot/grain/cli/bin/exec.js:64:10)
    at GrainCommand.listener [as _actionHandler] (/snapshot/grain/node_modules/commander/lib/command.js:488:17)
    at /snapshot/grain/node_modules/commander/lib/command.js:1227:65
    at GrainCommand._chainOrCall (/snapshot/grain/node_modules/commander/lib/command.js:1144:12)
    at GrainCommand._parseCommand (/snapshot/grain/node_modules/commander/lib/command.js:1227:27)
    at GrainCommand._dispatchSubcommand (/snapshot/grain/node_modules/commander/lib/command.js:1050:25)
    at GrainCommand._parseCommand (/snapshot/grain/node_modules/commander/lib/command.js:1193:19) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 8622,
  stdout: null,
  stderr: null
}
```

Edit: it looks like this actually only happens if the type alias is specifically a function. I just tried `type MyType = String` and there was no issue.

**Comment by phated** [comment]
Thanks for the report! We've been systematically fixing these as they are encountered. Our stdlib doesn't use any type aliases like that, so we haven't seen it.

**Comment by av8ta** [comment]
fyi this also crashes the lsp server with the same error in vscode.
