### ISSUE TITLE
LSP failure

### ISSUE THREAD

**Issue by ashtonmeuser** [grain-lang/grain#1851]
macOS 13.3.1
Grain [0.6.0 preview](https://github.com/grain-lang/grain/releases/tag/preview), ~~Grain [master 618c1ba](https://github.com/grain-lang/grain/commit/618c1ba309b19409ba57f2e2b610a55883a03a43)~~
Node 18.16.0

Running `grain lsp` fails with the following error. Same results with precompile package ~~and building from source.~~ Edit: Building from source (native compiler works) using `npm run compiler build`. This issue seems to hint at [Js_of_ocaml](https://ocsigen.org/js_of_ocaml/latest/manual/overview) although I have no certainty of that and zero experience with that tool.

```
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module './grainlsp.bc.js'
Require stack:
- /Users/ashtonmeuser/Projects/grain/cli/bin/grainlsp.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/ashtonmeuser/Projects/grain/cli/bin/grainlsp.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/ashtonmeuser/Projects/grain/cli/bin/grainlsp.js' ]
}

Node.js v18.16.0
node:child_process:960
    throw err;
    ^

Error: Command failed: "/Users/ashtonmeuser/.nvm/versions/node/v18.16.0/bin/node" /Users/ashtonmeuser/Projects/grain/cli/bin/grainlsp.js --stdlib /Users/ashtonmeuser/Projects/grain/stdlib
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at GrainCommand.execGrainlsp (/Users/ashtonmeuser/Projects/grain/cli/bin/exec.js:114:10)
    at GrainCommand.listener [as _actionHandler] (/Users/ashtonmeuser/Projects/grain/node_modules/commander/lib/command.js:488:17)
    at /Users/ashtonmeuser/Projects/grain/node_modules/commander/lib/command.js:1227:65
    at GrainCommand._chainOrCall (/Users/ashtonmeuser/Projects/grain/node_modules/commander/lib/command.js:1144:12)
    at GrainCommand._parseCommand (/Users/ashtonmeuser/Projects/grain/node_modules/commander/lib/command.js:1227:27)
    at GrainCommand._dispatchSubcommand (/Users/ashtonmeuser/Projects/grain/node_modules/commander/lib/command.js:1050:25)
    at GrainCommand._parseCommand (/Users/ashtonmeuser/Projects/grain/node_modules/commander/lib/command.js:1193:19) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 90613,
  stdout: null,
  stderr: null
}
```

**Comment by phated** [comment]
@ashtonmeuser As you noted, this issue is that you don't have a compiler built. The CLI that is being run is from `/Users/ashtonmeuser/Projects/grain/cli/bin/` which means you have the "from source" CLI linked into your path without a compiler built.

You could remove that and install the prebuilt binary into your path, but the two don't work together. If you are able to build from source, we highly recommend that.
