### ISSUE TITLE
Stdlib: Map tests fail with optimizations disabled

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#213]
While trying to debug an issue, I found that the `map.gr` implementation fails with optimizations disabled:

```
$ grain compiler/test/stdlib/map.test.gr -f "--O0"
S [GrainError]: modulo by zero
    at E (/Users/phated/github/grain/runtime/dist/grain-runtime.js:1:29897)
    at GRAIN$LAM_61 (<anonymous>:wasm-function[91]:0x4366)
    at GRAIN$LAM_59 (<anonymous>:wasm-function[89]:0x3908)
    at _start (<anonymous>:wasm-function[78]:0x22a0)
    at e.start (/Users/phated/github/grain/runtime/dist/grain-runtime.js:1:19362)
    at C.start (/Users/phated/github/grain/runtime/dist/grain-runtime.js:1:32993)
    at j.runFile (/Users/phated/github/grain/runtime/dist/grain-runtime.js:1:35925)
    at async run (/Users/phated/github/grain/cli/bin/run.js:14:7) {
  code: 18
}
```

**Comment by phated** [comment]
I just ran this command on master and it looks like it is fixed, so I'm closing this.

We already have another issue to enable testing with optimizations disabled in CI, so I'm going to say that succeeds this.
