### ISSUE TITLE
RuntimeError: function signature mismatch when using modulo

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#651]
```grain
print((25.5 % 1))
```
Running the code above gives the resulting error below. i am using the linux prepackaged binary in wsl
```sh
RuntimeError: function signature mismatch
    at <anonymous>:wasm-function[111]:0x65f5
    at <anonymous>:wasm-function[85]:0x466e
    at <anonymous>:wasm-function[65]:0x3e9e
    at <anonymous>:wasm-function[202]:0x11478
    at _start (<anonymous>:wasm-function[203]:0x114ca)
    at t.start (/snapshot/grain/runtime/dist/grain-runtime.js:1:21688)
    at u.start (/snapshot/grain/runtime/dist/grain-runtime.js:1:2407)
    at s.runFile (/snapshot/grain/runtime/dist/grain-runtime.js:1:172540)
    at async Object.run (/snapshot/grain/cli/bin/run.js:18:7)
```

**Comment by spotandjake** [comment]
```
print(25.5 | 0)
```
The bitwise or seems to cause the issue as well
