### ISSUE TITLE
fdWrite produces a range error

### ISSUE THREAD

**Issue by technosophos** [grain-lang/grain#675]
I am having trouble getting `File.fdWrite` to write to STDOUT or STDERR.

Version:

```
Grain cli 0.3.0
Grain compiler 0.3.0
```
On macOS 11.3.1 (and grain installed with Homebrew)

Minimum reproducible case:

```
import File from "sys/file"
File.fdWrite(File.stdout, "this is a test")
```

The above fails with the following runtime error:

```console
$ grain fdwrite.gr
RangeError: Invalid typed array length: 544434464
    at new Uint8Array (<anonymous>)
    at /snapshot/grain/runtime/dist/grain-runtime.js:1:10741
    at Function.from (<anonymous>)
    at X (/snapshot/grain/runtime/dist/grain-runtime.js:1:10643)
    at /snapshot/grain/runtime/dist/grain-runtime.js:1:14198
    at /snapshot/grain/runtime/dist/grain-runtime.js:1:8162
    at <anonymous>:wasm-function[304]:0x16550
    at <anonymous>:wasm-function[361]:0x1b749
    at <anonymous>:wasm-function[373]:0x1e4e8
    at _start (<anonymous>:wasm-function[374]:0x1e530)
```

If I compile and then run it via `wasmtime`, I get the same Wasm error:

```console
$ wasmtime fdwrite.gr.wasm 
SystemError: Bad address.
Error: failed to run main module `fdwrite.gr.wasm`

Caused by:
    0: failed to invoke command default
    1: wasm trap: unreachable
       wasm backtrace:
         0: 0x2a22 - <unknown>!<wasm function 55>
         1: 0x1b7ae - <unknown>!<wasm function 361>
         2: 0x1e4e8 - <unknown>!<wasm function 373>
         3: 0x1e530 - <unknown>!<wasm function 374>
```

**Comment by ospencer** [comment]
Hey @technosophos! I've got a fix for this in #677 and we'll get it into the next Grain release. Thanks for reporting!
